# Generated by Django 5.1.15 on 2026-09-14 16:43

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("schools", "0002_alter_school_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teachers",
                to="schools.school",
                verbose_name="Schule",
            ),
        ),
        migrations.CreateModel(
            name="TeacherInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="E-Mail-Adresse"),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Vorname"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Nachname"
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=accounts.models.generate_invitation_token,
                        editable=False,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=accounts.models.default_invitation_expiry
                    ),
                ),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="schools.school",
                        verbose_name="Schule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Einladung",
                "verbose_name_plural": "Einladungen",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TeacherAccessRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=150, verbose_name="Vorname"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=150, verbose_name="Nachname"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="E-Mail-Adresse"),
                ),
                ("message", models.TextField(blank=True, verbose_name="Nachricht")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Offen"),
                            ("approved", "Genehmigt"),
                            ("rejected", "Abgelehnt"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_requests",
                        to="schools.school",
                        verbose_name="Schule",
                    ),
                ),
                (
                    "invitation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_requests",
                        to="accounts.teacherinvitation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zugangsanfrage",
                "verbose_name_plural": "Zugangsanfragen",
                "ordering": ["-created_at"],
            },
        ),
    ]
