# Generated by Django 5.1.15 on 2026-09-14 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Inhaber"),
                            ("collaborator", "Kollege/Kollegin"),
                        ],
                        default="owner",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Klassen-Zugehörigkeit",
                "verbose_name_plural": "Klassen-Zugehörigkeiten",
            },
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Name der Schule"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schools_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Schule",
                "verbose_name_plural": "Schulen",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SchoolClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Klassenbezeichnung"),
                ),
                (
                    "subject",
                    models.CharField(blank=True, max_length=100, verbose_name="Fach"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes",
                        to="schools.school",
                    ),
                ),
                (
                    "teachers",
                    models.ManyToManyField(
                        related_name="classes",
                        through="schools.ClassMembership",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Klasse",
                "verbose_name_plural": "Klassen",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="classmembership",
            name="school_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="schools.schoolclass",
            ),
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=150, verbose_name="Anzeigename"),
                ),
                (
                    "access_code",
                    models.CharField(editable=False, max_length=16, unique=True),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="aktiv")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="schools.schoolclass",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schüler/in",
                "verbose_name_plural": "Schüler/innen",
                "ordering": ["display_name"],
            },
        ),
        migrations.AddConstraint(
            model_name="classmembership",
            constraint=models.UniqueConstraint(
                fields=("school_class", "teacher"), name="unique_teacher_per_class"
            ),
        ),
    ]
