# Generated by Django 5.1.15 on 2026-09-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0002_alter_school_created_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={
                "ordering": ["number", "display_name"],
                "verbose_name": "Schüler/in",
                "verbose_name_plural": "Schüler/innen",
            },
        ),
        migrations.AddField(
            model_name="student",
            name="number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Nummer"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="display_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Anzeigename"
            ),
        ),
        migrations.AddConstraint(
            model_name="student",
            constraint=models.UniqueConstraint(
                fields=("school_class", "number"), name="unique_number_per_class"
            ),
        ),
    ]
