# Generated by Django 5.1.15 on 2026-09-14 18:49

import django.db.models.deletion
import worksheets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0003_alter_student_options_student_number_and_more"),
        ("worksheets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="collect_submissions",
            field=models.BooleanField(
                default=True,
                help_text="Wenn aktiv, können Schüler/innen eine Lösung hochladen.",
                verbose_name="Abgaben einsammeln",
            ),
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="worksheets.assignment",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="schools.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abgabe",
                "verbose_name_plural": "Abgaben",
                "ordering": ["student__number"],
            },
        ),
        migrations.CreateModel(
            name="SubmissionFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=worksheets.models.submission_upload_path
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("size", models.PositiveIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="worksheets.submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abgabe-Datei",
                "verbose_name_plural": "Abgabe-Dateien",
                "ordering": ["uploaded_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="submission",
            constraint=models.UniqueConstraint(
                fields=("assignment", "student"), name="unique_submission_per_student"
            ),
        ),
    ]
